export const dummyProducts = [
  {
    id: 1,
    name: "Alpha Running Shoes",
    color: "Red",
    price: "$120",
    href: "/products/alpha-running-shoes",
    imageSrc: "/images/600x400.png",
    imageAlt: "Alpha Running Shoes in Red",
  },
  {
    id: 2,
    name: "Beta Sports T-Shirt",
    color: "Blue",
    price: "$35",
    href: "/products/beta-sports-tshirt",
    imageSrc: "/images/600x400.png",
    imageAlt: "Beta Sports T-Shirt in Blue",
  },
  {
    id: 3,
    name: "Gamma Fitness Shorts",
    color: "Black",
    price: "$45",
    href: "/products/gamma-fitness-shorts",
    imageSrc: "/images/600x400.png",
    imageAlt: "Gamma Fitness Shorts in Black",
  },
  {
    id: 4,
    name: "Delta Yoga Mat",
    color: "Purple",
    price: "$60",
    href: "/products/delta-yoga-mat",
    imageSrc: "/images/600x400.png",
    imageAlt: "Delta Yoga Mat in Purple",
  },
];
